INSERT INTO projects (title "Proj_one", funding_goal 100, start_date "May 1", end_date "Jan 5");
INSERT INTO projects (title "Proj_two", funding_goal 200, start_date "May 2", end_date "Jan 6");
INSERT INTO projects (title "Proj_three", funding_goal 300, start_date "May 3", end_date "Jan 7");
INSERT INTO projects (title "Proj_four", funding_goal 400, start_date "May 4", end_date "Jan 8");
INSERT INTO projects (title "Proj_five", funding_goal 500, start_date "May 5", end_date "Jan 9");
INSERT INTO projects (title "Proj_six", funding_goal 600, start_date "May 6", end_date "Jan 10");
INSERT INTO projects (title "Proj_seven", funding_goal 700, start_date "May 7", end_date "Jan 11");
INSERT INTO projects (title "Proj_eight", funding_goal 800, start_date "May 8", end_date "Jan 12");
INSERT INTO projects (title "Proj_nine", funding_goal 900, start_date "May 9", end_date "Jan 13");
INSERT INTO projects (title "Proj_ten", funding_goal 1000, start_date "May 10", end_date "Jan 14");

INSERT INTO users (name "a", age 13);
INSERT INTO users (name "b", age 12);
INSERT INTO users (name "c", age 11);
INSERT INTO users (name "d", age 19);
INSERT INTO users (name "e", age 18);
INSERT INTO users (name "f", age 17);
INSERT INTO users (name "g", age 16);
INSERT INTO users (name "h", age 15);
INSERT INTO users (name "i", age 14);
INSERT INTO users (name "j", age 13);
INSERT INTO users (name "k", age 12);
INSERT INTO users (name "l", age 11);
INSERT INTO users (name "m", age 19);
INSERT INTO users (name "n", age 18);
INSERT INTO users (name "o", age 17);
INSERT INTO users (name "p", age 16);
INSERT INTO users (name "q", age 15);
INSERT INTO users (name "r", age 14);
INSERT INTO users (name "s", age 13);
INSERT INTO users (name "t", age 12);
INSERT INTO users (name "u", age 11);
