INSERT INTO projects ("Proj_one", 100, "May 1", "Jan 5");
INSERT INTO projects ( "Proj_two",  200, "May 2", "Jan 6");
INSERT INTO projects ( "Proj_three",  300, "May 3", "Jan 7");
INSERT INTO projects ( "Proj_four", 400, "May 4",  "Jan 8");
INSERT INTO projects ( "Proj_five",  500, "May 5", "Jan 9");
INSERT INTO projects ( "Proj_six",  600, "May 6", "Jan 10");
INSERT INTO projects ("Proj_seven", 700,"May 7", "Jan 11");
INSERT INTO projects ("Proj_eight", 800, "May 8", "Jan 12");
INSERT INTO projects ( "Proj_nine", 900, "May 9", "Jan 13");
INSERT INTO projects ( "Proj_ten", 1000, "May 10", "Jan 14");

INSERT INTO users ("a", 13);
INSERT INTO users (name "b", age 12);
INSERT INTO users (name "c", age 11);
INSERT INTO users (name "d", age 19);
INSERT INTO users (name "e", age 18);
INSERT INTO users (name "f", age 17);
INSERT INTO users (name "g", age 16);
INSERT INTO users (name "h", age 15);
INSERT INTO users (name "i", age 14);
INSERT INTO users (name "j", age 13);
INSERT INTO users (name "k", age 12);
INSERT INTO users (name "l", age 11);
INSERT INTO users (name "m", age 19);
INSERT INTO users (name "n", age 18);
INSERT INTO users (name "o", age 17);
INSERT INTO users (name "p", age 16);
INSERT INTO users (name "q", age 15);
INSERT INTO users (name "r", age 14);
INSERT INTO users (name "s", age 13);
INSERT INTO users (name "t", age 12);
INSERT INTO users (name "u", age 11);
