INSERT INTO projects ( "Proj_one", 100, "May 1", "Jan 5");
INSERT INTO projects ( "Proj_two", 200, "May 2", "Jan 6");
INSERT INTO projects ( "Proj_three", 300, "May 3", "Jan 7");
INSERT INTO projects ( "Proj_four", 400, "May 4",  "Jan 8");
INSERT INTO projects ( "Proj_five",  500, "May 5", "Jan 9");
INSERT INTO projects ( "Proj_six",  600, "May 6", "Jan 10");
INSERT INTO projects ("Proj_seven", 700,"May 7", "Jan 11");
INSERT INTO projects ("Proj_eight", 800, "May 8", "Jan 12");
INSERT INTO projects ( "Proj_nine", 900, "May 9", "Jan 13");
INSERT INTO projects ( "Proj_ten", 1000, "May 10", "Jan 14");

INSERT INTO users ("a", 13);
INSERT INTO users ("b", 12);
INSERT INTO users ("c", 13);
INSERT INTO users ("d", 14);
INSERT INTO users ("e", 15);
INSERT INTO users ("f", 16);
INSERT INTO users ("h", 17);
INSERT INTO users ("g", 18);
INSERT INTO users ("i", 19);
INSERT INTO users ("j", 11);
INSERT INTO users ("k", 12);
INSERT INTO users ("l", 13);
INSERT INTO users ("m", 14);
INSERT INTO users ("n", 15);
INSERT INTO users ("o", 16);
INSERT INTO users ("p", 17);
INSERT INTO users ("q", 18);
INSERT INTO users ("r", 19);
INSERT INTO users ("s", 11);
INSERT INTO users ("t", 12);
INSERT INTO users ("u", 13);
